@extends('frontend/layouts/simple_detailnav')


@section('content')
<div class="main-content projects-content">
                <div class="d-flex justify-content-between">
                    <h1 class="page-title pb-0 mb-4">
                        TETENTER GENERAL LOAN TERMS <br>
                        <small class="small_subtitle">Effective as of 15.04.2019</small>
                    </h1>
                    
                   <!--  <div class="page-cations">
                        <a href="{{URL::TO('')}}/files/Estateguru_General_Loan_Terms_V15-04-2019.pdf" class="btn btn-regular">
                            Download PDF file
                        </a>
                    </div> -->
                </div>
                <div class="terms-content">
                    <p><br />
<strong>1.&nbsp;&nbsp; &nbsp;General</strong><br />
1.1.&nbsp;&nbsp; &nbsp;These general loan terms (&quot;Loan Terms&quot;) apply to each loan granted via Tetenter and form, with the principal loan terms agreed in respect of the relevant loan, an integral loan contract in respect of that loan.<br />
1.2.&nbsp;&nbsp; &nbsp;In addition to the loan contract, the relations between a lender and a borrower, including the procedure, manner and scope of performance of certain rights and obligations under a loan contract, are regulated by the Tetenter user terms (&quot;User Terms&quot;), which in the relevant respects are deemed as part of each loan contract and the adherence to which by each other can be demanded by the borrower and lender in their relations.<br />
1.3.&nbsp;&nbsp; &nbsp;The lender&rsquo;s rights may, inter alia, be restricted by the rights of other lenders parties to the loan contracts entered into within the relevant project, and a lender undertakes to consider the interests of the relevant other lenders in enforcement of his or her rights. Also, the borrower undertakes to treat all lenders that are parties to the loan contracts entered into within the relevant project equally in similar circumstances and each lender can demand from the borrower performance of the relevant obligation.<br />
1.4.&nbsp;&nbsp; &nbsp;Among other things, the obligations arising from clause 1.3 to consider the rights of other lenders and to treat lenders equally are embodied in the distribution of payments received in satisfaction of financial obligations relating to a loan contract proportionally amongst all lenders, and the right of a lender to cancel a loan contract only in case the other loan contracts entered into within the same project are also cancelled at the same time. The User Terms regulate the above and certain other rights and obligations more particularly.</p>

<p><strong>2.&nbsp;&nbsp; &nbsp;Loan</strong><br />
By entering into a loan contract in accordance with the procedure provided for in the User Terms, the lender undertakes to grant a sum of money to the borrower by way of a loan, and the borrower undertakes to repay that sum of money to the lender. The currency and amount of the relevant sum, its manner of repayment and other matters referred to in these Loan Terms are specified in the principal loan terms of the relevant loan.</p>

<p><strong>3.&nbsp;&nbsp; &nbsp;Transfer of the loan amount</strong><br />
3.1.&nbsp;&nbsp; &nbsp;The loan amount is transferred to the borrower by the procedure provided for in the User Terms<br />
&nbsp;after entering into loan contract provided that all the following conditions have been satisfied:<br />
3.1.1.&nbsp;&nbsp; &nbsp;within the project in relation to which the loan is being granted, during the syndication period, loan contracts are entered into in an aggregate principal amount of at least the amount that corresponds to the minimum amount of the funding target specified by the borrower in the loan request made within that project;<br />
3.1.2.&nbsp;&nbsp; &nbsp;the borrower has validly established in favour of the security agent, no later than on the 15th day after the end of the syndication period, security/ies of the type and in the scope specified in the principal loan terms;<br />
3.2.&nbsp;&nbsp; &nbsp;The loan amount is not required to be transferred to the borrower if on the proposed day of transfer of the loan amount any event or circumstance described in clause 14.4 of these general terms subsists (or the relevant event or circumstance would occur as a result of the transfer of the loan amount).<br />
3.3.&nbsp;&nbsp; &nbsp;Theportal operator on behalf of the lender determines the satisfaction or non-satisfaction of the preconditions of payment of the loan amount its own reasonable discretion, with the provisions of clause 3.4 of these general loan terms to be taken into account.<br />
3.4.&nbsp;&nbsp; &nbsp;The security referred to in clause 3.1.2 of these general loan terms shall be established in form and substance satisfactory to the portal operator and, among other things:<br />
3.4.1.&nbsp;&nbsp; &nbsp;be established in favour of the security agent to secure obligations arising from all loan documents (including loan contract(s)) entered into for the funding of the project in relation to which the loan is being granted (including to secure the performance of the parallel obligation described in clause 14 (Agreement on parallel obligation)).&nbsp;<br />
3.5. In cases, in the scope and by the procedure provided for in the User Terms, the fees and other costs payable or reimbursable by the borrower shall be paid from the loan amount, in which case the loan amount is transferred to the borrower only in an amount it exceeds the relevant fees and costs.</p>

<p><strong>4.&nbsp;&nbsp; &nbsp;Purpose of the loan</strong><br />
The borrower must use the loan only for the purpose specified in the principal loan terms of the relevant loan and for the funding of the payment of fees and reimbursement of costs relating to that loan specified in the User Terms.</p>

<p><strong>5.&nbsp;&nbsp; &nbsp;Repayment of loan</strong><br />
The borrower must repay the loan amount to the lender in the manner specified in the principal loan terms as follows:<br />
&nbsp;<br />
5.1.&nbsp;&nbsp; &nbsp;if according to the principal loan terms the loan is repayable in full at end of the loan period, the borrower must repay the loan amount in full on the last day of the loan period specified in the principal loan terms;<br />
5.2.&nbsp;&nbsp; &nbsp;if according to the principal loan terms the loan is repayable in instalments pursuant to the repayment schedule, the borrower must repay the principal amount of the loan in instalments such that on each repayment date shown in the relevant column of the repayment schedule referred to in clause 8 (Repayment schedule and interest payment schedule) of these Loan Terms, the borrower must repay the principal amount of the loan by the amount of the payment instalment shown in the relevant column of the repayment schedule opposite that repayment date.<br />
5.3.&nbsp;&nbsp; &nbsp;in case the object of the project consists of several immovables, incl. where such immovables are constructed as a result of the development activity conducted within the framework of the project and if pursuant to the principal loan terms the borrower has the right to return the loan in instalments upon the sale of each immovable, the loan shall be returned in instalments upon the sale of each immovable which constitutes a part of the project in accordance with the return rate set out in the principal terms of loan and the collateral agreement, but in any case the amount of the loan in full shall be repaid no later than by the last day of loan period.</p>

<p><strong>6.&nbsp;&nbsp; &nbsp;Prepayment of the loan</strong><br />
6.1.&nbsp;&nbsp; &nbsp;The borrower can prepay the loan earlier by the procedure provided for in the User Terms in full by giving a prior notice to the portal operator of at least three working days.</p>

<p><strong>7.&nbsp;&nbsp; &nbsp;Interest</strong><br />
7.1.&nbsp;&nbsp; &nbsp;The borrower must pay interest on the loan.<br />
7.2.&nbsp;&nbsp; &nbsp;The interest rate payable on the loan is the interest rate referred to in the principal loan terms of the relevant loan expressed as a percentage rate per annum. A higher interest rate may be appointed by the borrower in the principal loan terms to a lender who within a single investment invests a loan amount higher than a given amount in the principle loan terms.<br />
7.3.&nbsp;&nbsp; &nbsp;Interest accrues on the outstanding balance of the loan amount for each day the relevant amount is used by the borrower (with the loan amount being deemed as being used by the borrower for so long and until it is repaid in accordance with the procedure provided for in the loan contract).<br />
7.4.&nbsp;&nbsp; &nbsp;The borrower must pay interest with the frequency specified in the principal loan terms as follows:<br />
7.4.1.&nbsp;&nbsp; &nbsp;if according to the principal loan terms the loan is repayable and interest is payable in full at the end of the loan period, the borrower shall pay interest for the whole loan period no later than on the last day of the loan period;<br />
7.4.2.&nbsp;&nbsp; &nbsp;if according to the principal loan terms the loan is repayable in full at the end of the loan period but interest is payable periodically in monthly, quarterly, semi-annual or annual payments<br />
&nbsp;pursuant to the interest payment schedule, the borrower shall pay interest by periodical payments such that on each interest payment date shown in the relevant column of the interest payment schedule referred to in clause 8 (Repayment schedule and interest payment schedule) of these Loan Terms, the borrower shall pay interest in the amount shown in the relevant column of the interest payment schedule opposite that interest payment date;<br />
7.4.3.&nbsp;&nbsp; &nbsp;if according to the principal loan terms the loan is repayable in instalments pursuant to the repayment schedule, the borrower shall pay interest simultaneously with the relevant repayment instalment in the amount shown in the relevant column of the repayment schedule applicable to the relevant loan opposite that repayment instalment.<br />
7.5.&nbsp;&nbsp; &nbsp;In case of prepayment of the loan in full in accordance with the procedure provided for in clause 6 (of the loan) of the Loan Terms, the borrower shall pay to the lender unpaid interest accrued until the date of repayment of the loan together with the repayment of the principal amount of the loan.</p>

<p><br />
<strong>8.&nbsp;&nbsp; &nbsp;Repayment schedule and interest payment schedule</strong><br />
8.1.&nbsp;&nbsp; &nbsp;The repayment schedule or interest payment schedule applicable to a loan is drawn up and sent to the lender and borrower in accordance with the procedure provided for in the User Terms at the same time with transfer of the loan amount to the borrower. The repayment schedule and interest payment schedule applicable to a loan is drawn up, among other things, in accordance with the following principles:<br />
8.1.1.&nbsp;&nbsp; &nbsp;if according to the principal loan terms the type of the repayment schedule is &ldquo;annuity payments&rdquo;, repayments of the principal amount of the loan, and interest payable in respect of the whole loan period, are divided, as specified in the principal loan terms, into monthly, quarterly, semi- annual or annual periodical payments such that the borrower must make a payment of an equal amount after the expiry of each relevant period;<br />
8.1.2.&nbsp;&nbsp; &nbsp;if according to the principal loan terms the type of the repayment schedule is &ldquo;principal amount in equal instalments&quot;, the repayments of the principal amount of the loan are divided, as specified in the principal loan terms, into monthly, quarterly, semi-annual or annual periodical repayment instalments of equal amounts to which interest payable in respect of the period preceding that repayment instalment (including for the repayment date of that instalment) is added;<br />
8.1.3.&nbsp;&nbsp; &nbsp;if according to the principal loan terms the principal amount of the loan is supposed to be paid back as a single payment in the end of the loan period, the interest payable in respect of the whole loan period is divided, as specified in the principal loan terms, into monthly, quarterly, semi-annual or annual periodical payments of equal amounts;<br />
8.1.4.&nbsp;&nbsp; &nbsp;notwithstanding the above, any payment to be made pursuant to the repayment schedule or interest payment schedule of a loan may be required to be made following the lapse of a period shorter than a month, quarter, semi-annum or annum where, among other things, it is necessary for the purposes of the borrower being able to make the relevant payments on a day falling on the date for making payments relating to repayment of the loan as specified in the principal loan terms and/or&nbsp;for the purposes of ensuring that the due date of repayment of the principal amount or of making interest and other payments related to the loan does not fall on a day which is not a working day or on a date falling later than the last day of the loan period.<br />
8.2.&nbsp;&nbsp; &nbsp;The repayment schedule and/or interest payment schedule applicable to the relevant loan sent to the lender and the borrower may change, among other things, as a result of amendments to the loan contract, delays in any payments to be made by the borrower and/or the occurrence of other similar events. If the relevant changed repayment schedule and/or interest payment schedule is sent to the borrower, the changed repayment schedule and/or interest payment schedule replaces the relevant schedule that had previously been sent to the borrower.</p>

<p><strong>9.&nbsp;&nbsp; &nbsp;Default interest</strong><br />
9.1.&nbsp;&nbsp; &nbsp;In case of delay in the performance of a financial obligation, the borrower shall pay default interest. Default interest is calculated from the moment the financial obligation becomes due until its due performance, unless it is otherwise stated in the User Terms or the Loan Terms.<br />
9.2.&nbsp;&nbsp; &nbsp;The rate of default interest is the interest rate referred to in the principal loan terms to which fifteen per cent (15%) per annum is added.<br />
For example: if the interest rate provided for in the principal loan terms is 10% per annum, the default interest, which shall be calculated from the arrears from the moment the obligation becomes due until it is performed, is 25% per annum.</p>

<p><strong>10.&nbsp;&nbsp; &nbsp;Other payments and fees related to the loan contract</strong><br />
10.1.&nbsp;&nbsp; &nbsp;The borrower shall, in a timely and otherwise due manner, pay all fees and compensate all losses, fees, costs and duties the payment and/or compensation of which is the borrower&rsquo;s obligation according to the User Terms (including fees, duties, costs and losses payable and/or reimbursable to the portal operator and security agent).<br />
10.2.&nbsp;&nbsp; &nbsp;The cost of the conclusion of a notarised collateral agreement (mainly the notary fees) shall be borne by the Borrower.<br />
10.3.&nbsp;&nbsp; &nbsp;In cases specified in the user terms, the fees and costs referred to in clause 10.1 of the Loan Terms are shown in the relevant column of the repayment schedule or interest payment schedule referred to in clause 8 (Repayment schedule and interest payment schedule) of these Loan Terms, in which case the borrower shall pay the relevant fees and costs on the repayment date or interest payment date in an amount shown in the relevant column opposite that repayment date or interest payment date.</p>

<p><strong>11.&nbsp;&nbsp; &nbsp;Other obligations related to borrower&rsquo;s activity</strong><br />
11.1.&nbsp;&nbsp; &nbsp;The borrower shall refrain from transactions and acts in its activities that are beyond the scope of everyday economic activities of the borrower or as the result of which the borrower&rsquo;s ability to timely and duly perform the obligations arising from the loan documents relating to the loan granted within the project may materially reduce. Among other things, the borrower may not:<br />
&nbsp;11.1.1.&nbsp;&nbsp; &nbsp;make payments to its direct or indirect owners (including shareholders) (&ldquo;owners&rdquo;), members of management board or supervisory council (&ldquo;members of the governing body&rdquo;) or persons connected with the borrower, the members of the borrower&rsquo;s governing body or owners, or other persons related to the borrower, members of the borrower&rsquo;s governing body or owners, by way of distributions or fees or by way of payments made in discharge of debt obligations or other payments (with the above not restricting the making of payments by the borrower of fees of members of the governing body, salaries or other ordinary employment related payments in the ordinary course of its everyday economic activities provided that the relevant payments are made with a view to discharging its obligations arising from contract or law in a reasonable amount on arm&rsquo;s length terms or on terms more favourable for the borrower than the arm&rsquo;s length terms);<br />
11.1.2.&nbsp;&nbsp; &nbsp;encumber its assets (including the real property the subject of the project to which the loan relates) with a restricted real right or other right of a third person (including with securities);<br />
11.1.3.&nbsp;&nbsp; &nbsp;dispose of the real property the subject of the project to which the loan relates, or any other material assets;<br />
11.1.4.&nbsp;&nbsp; &nbsp;take out a loan or credit or incur other financial indebtedness which according to the generally accepted accounting principles in Estonia are treated as borrowings (laenukohustused) (the relevant loan, credit and other financial indebtedness hereinafter the &ldquo;loan obligations&rdquo;), except for the loans taken via Tetenter;<br />
11.1.5.&nbsp;&nbsp; &nbsp;guarantee, provide surety or otherwise secure the obligations of any person;<br />
11.1.6.&nbsp;&nbsp; &nbsp;reduce its share capital; or<br />
11.1.7.&nbsp;&nbsp; &nbsp;be the subject of merger, division or transformation, except in cases and to the extent the relevant act or activity described in clauses 11.1.1 to 11.1.7 above was expressly contemplated in the business plan, activity plan or other relevant project description of the relevant project made available to the lender in the portal before entry into the loan contract, or if the portal operator on behalf of the lender gives its prior consent in a format which can be reproduced in writing.<br />
11.2.&nbsp;&nbsp; &nbsp;The borrower must refrain from transactions and acts that may materially reduce the value or scope of security or otherwise prejudice the enforcement of security.<br />
11.3.&nbsp;&nbsp; &nbsp;The borrower must adhere to the business plan, activity plan and budget made available to the lender for the lender&rsquo;s inspection within the project to which the loan relates except in case deviation from it does not, in the opinion of the lender, prejudice the interests of the lender.<br />
11.4.&nbsp;&nbsp; &nbsp;The borrower undertakes to keep its assets (including the real property provided as a security) and activities insured against the risks and to the extent as is usual for persons carrying on similar activities or for similar projects and deliver to the lender copies of the relevant insurance policies at the lender&rsquo;s request. Where the insurance policies have not been provided within 3 business days upon the receipt of the respective request, the portal operator on behalf of lenders has the right to claim from the borrower a penalty fee in the amount of 500 (five hundred) euros and to obtain insurance at their own discretion.<br />
11.5.&nbsp;&nbsp; &nbsp;The penalty claim does not exclude the implementation of other measures, such as cancellation of the loan contracts or damage claims.<br />
11.6.&nbsp;&nbsp; &nbsp;The borrower undertakes to duly follow and comply with the provisions of the User Terms and any laws and other regulations applicable to it.</p>

<p><strong>12.&nbsp;&nbsp; &nbsp;Borrower&rsquo;s notification obligations</strong><br />
11.7.&nbsp;&nbsp; &nbsp;The borrower shall, in the manner provided for in the User Terms, notify:<br />
12.1.1.&nbsp;&nbsp; &nbsp;promptly upon such change, of a change of its name, postal address, e-mail address or other information required in the User Terms;<br />
12.1.2.&nbsp;&nbsp; &nbsp;promptly upon becoming aware of the same, of the commencement of court, arbitral tribunal, bankruptcy, rehabilitation (saneerimine), enforcement or administrative proceedings in respect of the borrower, the borrower&rsquo;s assets, an asset subject to loan security or the provider of loan security or its assets, if the relevant proceeding concerns proprietary obligations (varalised kohustused) with an aggregate value of at least EUR 1,000, and provide details of the substance of the relevant proceeding;<br />
12.1.3.&nbsp;&nbsp; &nbsp;promptly upon becoming aware of the same, of any other circumstances or events concerning the borrower, borrower&rsquo;s assets, the assets subject to loan security, the provider of loan security or its assets, with regard to which a lender would have, having regard to the purpose of the loan contract, a reasonably recognisable interest (including any relevant circumstances and events concerning the project to which the loan relates and circumstances and events concerning the real property the subject of that project (including of events described in clause 14.4.6 or 11.1.2 of these Loan Terms)).<br />
12.2.&nbsp;&nbsp; &nbsp;On request of the lender, the borrower must promptly provide any data and information requested by the lender about the circumstances and events concerning the borrower, borrower&rsquo;s assets, the asset subject to loan security, provider of the loan security, use of the loan amount or its assets, including information about the progress of the project.<br />
12.3.&nbsp;&nbsp; &nbsp;The borrower shall, within fifteen (15) days of the relevant request by the lender, at its own cost commission and deliver to the lender, a valuation report of the real property/ies the subject of the project to which the loan relates or the subject of security, from a reputable and independent real estate bureau whose business includes valuation of real estate. The lender may not make such request more often than once during any half-year period except where in the lender&rsquo;s opinion the borrower has breached the loan contract or any other loan document (or the lender reasonably suspects that the relevant breach has occurred) or where in the lender&rsquo;s opinion other grounds for extraordinary cancellation of the loan contract may subsist, in which case the lender may make the relevant request more frequently.</p>

<p><strong>13.&nbsp;&nbsp; &nbsp;Payment defaults and other breaches</strong><br />
13.1.&nbsp;&nbsp; &nbsp;If the borrower delays the performance of any financial or non-financial obligation arising from<br />
&nbsp;loan documents related to the loan:<br />
13.1.1.&nbsp;&nbsp; &nbsp;default interest is calculated on the relevant obligation pursuant to the procedure provided for in clause 9 (Default interest) of these Loan Terms;<br />
13.1.2.&nbsp;&nbsp; &nbsp;in addition to those provided for in clause 13.1.1, other actions and steps described in clause 12 (Payment defaults and other breaches) of the User Terms may be taken with respect to the borrower in respect of that obligation; and<br />
13.1.3.&nbsp;&nbsp; &nbsp;in cases provided for in clause 14.4 of these Loan Terms, the lender may extraordinarily cancel the loan contract in accordance with the procedure provided for in the User Terms;<br />
13.1.4.&nbsp;&nbsp; &nbsp;in case of a loan contract described in clause 8.1.3. of these Loan Terms the borrower is obliged to pay indemnity provided for in clause 18.16 of the User Term.<br />
13.2.&nbsp;&nbsp; &nbsp;The provisions of clauses 13.1.2 and 13.1.3 of these general loan terms apply also in circumstances where the borrower breaches any non-financial obligation arising from the loan documents related to the loan or other grounds subsist for extraordinary cancellation of the loan contract.</p>

<p><strong>14.&nbsp;&nbsp; &nbsp;Termination of the loan contract</strong><br />
14.1.&nbsp;&nbsp; &nbsp;The loan contract terminates when the lender has been repaid the principal amount of the loan, and interest has been paid on it, in full, and the borrower has performed all other financial obligations arising from or on the basis of the loan documents related to the relevant loan, or in case the loan contract has been cancelled or withdrawn.<br />
14.2.&nbsp;&nbsp; &nbsp;The loan contract terminates automatically when any condition described in clauses 3.1.1 and/or 3.1.2 of these Loan Terms is not satisfied within the prescribed time period and procedure, or if the loan amount is not transferred to the borrower in circumstances described in clause 3.2 of these Loan Terms.<br />
14.3.&nbsp;&nbsp; &nbsp;The loan contract terminates automatically if before the transfer of the loan amount to the borrower:<br />
14.3.1.&nbsp;&nbsp; &nbsp;the user status of the lender or borrower is terminated by the procedure described in clause<br />
21.2 of the User Terms; or<br />
14.3.2.&nbsp;&nbsp; &nbsp;bankruptcy of the portal operator is declared or if the portal operator otherwise terminates its operation.<br />
14.4.&nbsp;&nbsp; &nbsp;The lender can cancel the loan contract extraordinarily in cases provided for in law or if at least one of the following circumstance or event has occurred:<br />
14.4.1.&nbsp;&nbsp; &nbsp;if according to the principal loan terms the loan is repayable in instalments pursuant to the repayment schedule and the borrower is in delay with the payment of an amount equal to two instalments, or with the payment of one instalment for more than 30 days (disregarding, for the purposes of calculating the amounts referred to above, interest payments related to the relevant instalments);<br />
14.4.2.&nbsp;&nbsp; &nbsp;the borrower fails to perform the obligation to pay interest or any other financial obligation arising from or on the basis of loan documents (excluding the obligation to repay the principal amount of the loan) and at least 14 days have elapsed from the day the relevant obligation fell due;<br />
14.4.3.&nbsp;&nbsp; &nbsp;the borrower breaches the obligation arising from clause 4 (Purpose of the loan), any obligation arising from clause 11 (Borrower&rsquo;s other obligations), or a material breach of any non- financial obligation arising from clause 12 (Borrower&rsquo;s notification obligations) or any other non- financial obligation arising from loan document related to the relevant loan occurs;<br />
14.4.4.&nbsp;&nbsp; &nbsp;any information or confirmations provided by the borrower occurs to be untrue, misleading or otherwise inaccurate in any material respect, or the borrower has failed to disclose information or circumstances with regard to which the lender would have had a recognisable significant interest having regard to the purpose of the loan contract;<br />
14.4.5.&nbsp;&nbsp; &nbsp;bankruptcy, rehabilitation (saneerimine) or liquidation proceedings have been commenced with respect to the borrower, or enforcement proceeding has been commenced with respect to the borrower concerning a monetary claim in an amount of at least EUR 1,000 (one thousand);<br />
14.4.6.&nbsp;&nbsp; &nbsp;the real property which is provided as a security to the loan is disposed of (notwithstanding the provisions of clause 11.1.3 of these Loan Terms), destructed or, to a material extent, damaged;<br />
14.4.7.&nbsp;&nbsp; &nbsp;if more than one loan contract is entered into within the project to which the loan relates and under any other loan contract any ground exists for extraordinary cancellation of that other loan contract;<br />
14.4.8.&nbsp;&nbsp; &nbsp;the persons who, at the time of making the loan request pursuant to which the loan contract was entered into, had direct or indirect control over the borrower, cease to have such control over the borrower, or a substantial part of the borrower&rsquo;s assets or undertaking is disposed of;<br />
14.4.9.&nbsp;&nbsp; &nbsp;any other financial obligation of the borrower or borrower&rsquo;s representative falls due and payable prematurely as a result of a breach of obligation or the occurrence of another similar event, or any other agreement entered into with the borrower or borrower&rsquo;s representative in respect of incurring a loan obligation is extraordinarily cancelled or is otherwise cancelled as a result of breach of agreement or the occurrence of another similar event, except where the aggregate amount of such financial obligations or the amount of loan or credit under such agreements does not exceed EUR 1,000; or<br />
14.4.10.&nbsp;&nbsp; &nbsp;if compulsory enforcement (sundt&auml;itmine) has been commenced in respect of the asset subject to security, or the value of the asset subject to security has, in the opinion of the lender, otherwise materially decreased (including in circumstances where the security concerned is a guarantee or suretyship (k&auml;endus) and, in the opinion of the lender, the creditworthiness of the person who had granted that security has materially deteriorated).<br />
14.5.&nbsp;&nbsp; &nbsp;In case of occurrence of the circumstance or event described in clause 14.4.10 of these Loan Terms, the lender may cancel the loan contract extraordinarily only where, within 14 days after the borrower became aware of or should have become aware of that circumstance or event, the borrower has not given additional security to the lender as a result of which the loan is secured in an equivalent<br />
&nbsp;extent and quality which it would have been in had the circumstance or event described in clause<br />
14.4.10 not occurred.<br />
14.6.&nbsp;&nbsp; &nbsp;For the purpose of clause 14.4.8 of these Loan Terms, it is deemed that a person has<br />
&bdquo;control&ldquo; over the borrower in circumstances where, among other things, at least one of the following conditions is satisfied:<br />
14.6.1.&nbsp;&nbsp; &nbsp;the person owns or controls (through shares, participations (osad) or other ownership instruments or pursuant to any agreement or mandate or otherwise (including through third person(s)):<br />
14.6.1.1.&nbsp;&nbsp; &nbsp;the majority of votes represented by shares, participations (osad) or other equivalent ownership instruments or membership rights in the borrower; or<br />
14.6.1.2.&nbsp;&nbsp; &nbsp;the right to appoint or recall the majority of the members of the supervisory council, management board or other similar governing body of the borrower;<br />
14.6.2.&nbsp;&nbsp; &nbsp;the person, while itself being the general or limited partner or shareholder of the borrower, alone controls the majority of votes pursuant to an agreement with other general partners, limited partners or shareholders or otherwise;<br />
14.6.3.&nbsp;&nbsp; &nbsp;the person has dominant influence or control over the borrower or has an opportunity to exercise it, or the person is otherwise able to control the operational and/or financial policies of the borrower.<br />
14.7.&nbsp;&nbsp; &nbsp;In case of extraordinary cancellation of the loan contract by the lender, the loan amount becomes immediately repayable in full and all other consequences provided for in law shall occur (with all payment obligations in respect of interest and other fees also falling due and payable). Clause 15 (Agreement on parallel obligation) of these Loan Terms remains in effect also after cancellation of the loan contract.<br />
14.8.&nbsp;&nbsp; &nbsp;The loan contract terminates, however the borrower is not obliged to repay the principle amount of the loan as a whole, in case the investor wishes to invest in a sequent project of the borrower (incl. based on the refinancing request with respect to the same project) and the investment of the investor is set off the claim of the principle amount of the loan according to the wish of the investor and an agreement of both the investor and the borrower. The borrower is, in the present case, obliged to repay all interest payment obligations and other fees and payments, also the share of the principle amount of the loan which overcomes the amount of the investment in the sequent project.</p>

<p><strong>15.&nbsp;&nbsp; &nbsp;Agreement on parallel obligation</strong><br />
15.1.&nbsp;&nbsp; &nbsp;This clause 15 (Agreement on parallel obligation) of the Loan Terms applies to each loan which, according to the principal loan terms of that loan, is a secured loan.<br />
15.2.&nbsp;&nbsp; &nbsp;The borrower undertakes to pay to the security agent an amount (such obligation of the borrower to the security agent hereinafter the &ldquo;parallel obligation&rdquo;) equal to and in the currency of<br />
&nbsp;each other monetary obligation of the borrower arising from any loan document related to the relevant loan (such other monetary obligation hereinafter the &ldquo;base obligation&rdquo;).<br />
15.3.&nbsp;&nbsp; &nbsp;The parallel obligation falls due and must be performed to the security agent at the same time and in the same currency when and in which the corresponding base obligation falls due and must be performed.<br />
15.4.&nbsp;&nbsp; &nbsp;The amount of the parallel obligation decreases from time to time in the extent by which the base obligation that corresponds to that parallel obligation is duly performed to the creditor for the time being of that base obligation (with such base obligation not being deemed to have been performed for such purposes until such creditor has irreversibly received the relevant amount in full), and the amount of the relevant base obligation decreases from time to time in the extent by which the parallel obligation that corresponds to that base obligation is duly performed to the security agent or to a person appointed by the security agent (with such parallel obligation not being deemed to have been performed for such purposes until the security agent or the person appointed by the security agent has irreversibly received the relevant amount in full).<br />
15.5.&nbsp;&nbsp; &nbsp;The security agent may demand the performance of the parallel obligation pursuant to the loan contract from the borrower independently on its own behalf and the borrower must perform the relevant obligation to the security agent or the person appointed by the security agent.</p>

<p><strong>16.&nbsp;&nbsp; &nbsp;Order of application of insufficient payments</strong><br />
16.1.&nbsp;&nbsp; &nbsp;If a payment made pursuant to a loan document (including loan contract) related to the relevant loan is not sufficient for the satisfaction of all obligations that have fallen due, that payment shall be applied:<br />
16.1.1.&nbsp;&nbsp; &nbsp;first, towards covering of costs incurred for collection of obligations (including covering of costs of the actions and steps referred to in clause 13.1 of the Loan Terms);<br />
16.1.2.&nbsp;&nbsp; &nbsp;second, towards covering of fees and costs that have not been paid to the portal operator and the security agent;<br />
16.1.3.&nbsp;&nbsp; &nbsp;third, towards covering of accrued default interest;<br />
16.1.4.&nbsp;&nbsp; &nbsp;fourth, towards covering of outstanding interest;<br />
16.1.5.&nbsp;&nbsp; &nbsp;fifth, towards covering of outstanding principal amount of the loan; and<br />
16.1.6.&nbsp;&nbsp; &nbsp;sixth, towards covering of all other payments and fees.<br />
16.2.&nbsp;&nbsp; &nbsp;If a payment is not sufficient for the full satisfaction of all obligations within the same priority level referred to in clause 16.1, that payment shall be applied towards covering the relevant obligations in a chronological order of such obligations falling due or in any other order at the choice of the lender.<br />
16.3.&nbsp;&nbsp; &nbsp;The order of application of payments arising from clause 16.1 applies insofar as the User Terms do not state otherwise.<br />
&nbsp;<br />
<strong>17.&nbsp;&nbsp; &nbsp;Procedure of payments</strong><br />
All payments related to loan contract and other loan documents shall be made in full in accordance with the procedure provided for in the User Terms, with the borrower not being entitled to set off any amounts owing by it or make any other deductions or withholdings from such amounts.</p>

<p><strong>18.&nbsp;&nbsp; &nbsp;Time units and periods</strong><br />
18.1.&nbsp;&nbsp; &nbsp;If not stated otherwise in the Loan Terms, the time units and periods referred to in the loan contract are interpreted and determined in accordance with the provisions of the User Terms.<br />
18.2.&nbsp;&nbsp; &nbsp;If in any calendar month there is no day that corresponds to the date for making payments specified in the principal loan terms of the relevant loan, the last working day of that calendar month shall be the due date of payment.</p>

<p><strong>19.&nbsp;&nbsp; &nbsp;Notices relating to this contract</strong><br />
All notices related to the loan contract shall be delivered in the format and in the manner provided for in the User Terms.</p>

<p><strong>20.&nbsp;&nbsp; &nbsp;Transfer of rights and obligations</strong><br />
20.1.&nbsp;&nbsp; &nbsp;The borrower may assign or otherwise transfer the rights and/or obligations arising from the loan documents relating to the loan only with the consent of the portal operator (or any legal successor of the portal operator from time to time) and with the consent of the security agent (or any legal successor of the security agent from time to time).<br />
20.2.&nbsp;&nbsp; &nbsp;The lender may assign or otherwise transfer the rights and/or obligations arising from the loan documents relating to that loan only with the consent of the portal operator (or any legal successor of the portal operator from time to time) and with the consent of the security agent (or any legal successor of the security agent from time to time).<br />
20.3.&nbsp;&nbsp; &nbsp;Notwithstanding the provisions of clauses 20.1 and 20.2, the rights and/or obligations arising from loan documents may only be assigned or otherwise transferred if the same is expressly contemplated and permitted in the User Terms, and only in the manner and in accordance with the procedure provided for in the User Terms.</p>

<p><strong>21.&nbsp;&nbsp; &nbsp;Portal operator&rsquo;s powers</strong><br />
21.1.&nbsp;&nbsp; &nbsp;The lender and the borrower have agreed that the portal operator (or any legal successor of the portal operator from time to time) administrates the loan and the portal operator acts as a representative of the lender in the relations between the lender and the borrower notwithstanding any potential conflict of interests. The authorization hereby given to the portal<br />
&nbsp;operator is irrevocable.<br />
21.2.&nbsp;&nbsp; &nbsp;If pursuant to a loan document relating to the loan a consent of the lender is required for any act or activity, or if the subsistence of any circumstance or event, or the satisfaction of any condition, is to be determined by the lender, the portal operator gives the relevant consent or determines the relevant matter on the lender&rsquo;s behalf at its own discretion.<br />
21.3.&nbsp;&nbsp; &nbsp;The portal operator is entitled to rely on clauses 21.1 and 21.2 of the Loan Terms and independently on its own behalf demand the performance of the same.<br />
21.4.&nbsp;&nbsp; &nbsp;The portal operator on behalf of the lenders is entitled to reduce the rate of the default interest provided in the clause 9.1 or to waive the right to the interest entirely if it is, in the opinion of the poral operator in &nbsp;the best interests of the lender and necessary to simplify collecting the principal amount of the loan and accumulated interest.&nbsp;<br />
21.5.&nbsp;&nbsp; &nbsp;The more particular role and scope of powers of the portal operator may be provided for in the User Terms.</p>

<p><strong>22.&nbsp;&nbsp; &nbsp;Interpretation of the loan contract</strong><br />
If not otherwise expressly stated in these Loan Terms, among other things, the rules and explanations provided for in the User Terms apply to the interpretation of the loan contract. If the User Terms have ascribed a certain meaning or explanation to the word or expression used in the principal loan terms and/or these Loan Terms, such meaning and/or explanation shall apply also to the interpretation of the principal loan terms and/or these Loan Terms.</p>

<p><strong>23.&nbsp;&nbsp; &nbsp;Conditions not regulated in the loan contract</strong><br />
The parties follow the provisions of law in relation to any matters not regulated in the loan contract and the User Terms.</p>

<p><strong>24.&nbsp;&nbsp; &nbsp;Governing law and procedure for solving disputes</strong><br />
The provisions of the User Terms in respect of governing law, jurisdiction and resolving of disputes shall apply with respect to the lender and borrower.</p>

                </div>
                </div>
            </div>
        </div>
    </div>
</section>


@stop